on:
  release:
    types: [created]

env:
  CMD_PATH: ./cmd/jc2aws
  CGO_ENABLED: 0

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release jc2aws
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Set APP_VERSION env
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "${{ env.CMD_PATH }}"
          goversion: "1.24.5"
          binary_name: "jc2aws"
          overwrite: true
          md5sum: false
          sha256sum: true
          build_flags: -v
          ldflags: -s -w -extldflags -static -X "github.com/yousysadmin/jc2aws/pkg.Version=${{ env.APP_VERSION }}"
          asset_name: "jc2aws-${{env.APP_VERSION}}-${{ matrix.goos }}-${{ matrix.goarch }}"
